" Show (partial) command in status line
set showcmd

" Enter spaces when tab is pressed
set expandtab
set tabstop=4

" Number of spaces for auto indent
set shiftwidth=4
set autoindent

" Show matching brackets when indicator is over them
set showmatch

" Enable syntax higlighting
syntax enable

" Always show current position
set ruler

" Show line numbers
set number

" Setting colorscheme
try
    colorscheme unokai
catch
endtry

" Sets background to transparent
hi Normal guibg=NONE ctermbg=NONE

" Return to last edit position when opening files (You want this!)
au BufReadPost * if line("'\"") > 1 && line("'\"") <= line("$") | exe "normal! g'\"" | endif

" Cursor config
"   Ps = 0  -> blinking block.
"   Ps = 1  -> blinking block (default).
"   Ps = 2  -> steady block.
"   Ps = 3  -> blinking underline.
"   Ps = 4  -> steady underline.
"   Ps = 5  -> blinking bar (xterm).
"   Ps = 6  -> steady bar (xterm).
let &t_SI = "\e[6 q"
let &t_EI = "\e[2 q"

